# Generated by Django 3.2.4 on 2021-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=500)),
                ('pcategory', models.CharField(default='', max_length=500)),
                ('pprice', models.FloatField(blank=True, null=True)),
                ('pimage', models.ImageField(default='', upload_to='Products')),
            ],
        ),
    ]
