# Generated by Django 3.2.4 on 2021-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pflavor',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='pwt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='pcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='pname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
