# Generated by Django 3.2.4 on 2021-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20210605_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=50)),
                ('pcategory', models.CharField(default='', max_length=50)),
                ('pmolecule', models.CharField(blank=True, default='', max_length=50)),
                ('pprice', models.FloatField(blank=True, null=True)),
                ('pimage', models.ImageField(default='', upload_to='Products')),
                ('pwt', models.CharField(blank=True, default='', max_length=50)),
                ('pflavor', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
