# Generated by Django 3.2.4 on 2021-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pflavor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
