# Generated by Django 3.2.4 on 2021-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0004_alter_products_pflavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=50)),
                ('pcategory', models.CharField(default='', max_length=50)),
                ('pprice', models.FloatField(blank=True, null=True)),
                ('pimage', models.ImageField(default='', upload_to='Products')),
                ('pwt', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
