# Generated by Django 3.2.4 on 2021-06-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='usercart',
        ),
    ]
