# Generated by Django 3.2.4 on 2021-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0006_rename_cart_usercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('pname', models.CharField(default='', max_length=50)),
                ('pprice', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
