# Generated by Django 3.2.4 on 2021-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
