# Generated by Django 3.2.4 on 2021-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0008_orders_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='pname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
