# Generated by Django 3.2.4 on 2021-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0009_usercart_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pwt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
