# Generated by Django 3.2.4 on 2021-06-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0010_alter_products_pwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pqty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
